### ISSUE TITLE
Issue installing CraftBeerPi on new Raspbian install

### ISSUE THREAD

**Issue by dwyszynski** [Manuel83/craftbeerpi#69]
Freshly installed Raspbian from NOOBS.  RPI 2

While running the install I get the below, any help would be appreciated.  

libpcre3-dev is already the newest version.

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Downloading/unpacking blinker==1.3 (from -r requirements.txt (line 1))

Cleaning up...

Exception:

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main

    status = self.run(options, args)

  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run

    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle
)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files

    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)

  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 194, in find_requirement

    page = self._get_page(main_index_url, req)

  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_page
    session=self.session,

  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 694, in get_page
    req, link, "connection error: %s" % exc, url,

TypeError: __str__ returned non-string (type Error)

Storing debug log for failure in /root/.pip/pip.log

**Comment by dwyszynski** [comment]
I figured out the issue, my time/date was off and that made all the difference!  Hopefully this helps someone!
